# Generated by Django 3.1.4 on 2020-12-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='owner',
            table='owner',
        ),
    ]
