# Generated by Django 3.1.4 on 2020-12-18 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20201218_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'владелец', 'verbose_name_plural': 'владелецы'},
        ),
        migrations.AddField(
            model_name='owner',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
