# Generated by Django 3.1.4 on 2020-12-18 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20201218_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
                ('type', models.CharField(max_length=20, verbose_name='тып')),
            ],
            options={
                'verbose_name': 'жывотни',
                'verbose_name_plural': 'животные',
                'db_table': 'animal',
            },
        ),
        migrations.AlterField(
            model_name='owner',
            name='age',
            field=models.IntegerField(verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='фамиля'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=25, verbose_name='имя'),
        ),
    ]
